version: '3.1'

services:
  web:
    build: docker-file
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./application/:/var/www/
      - ./docker-file/custom.ini:/usr/local/lib/conf.d/custom.ini
    links:
      - db:db
  db:
    image: mariadb:10.3
    restart: always
    volumes:
      - ./.db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3310:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    links:
      - db:db    
